spring.application.name=characters-api
spring.datasource.url=jdbc:postgresql://ep-aged-queen-ai0fvz1l-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.jpa.hibernate.ddl-auto=update
spring.datasource.username=neondb_owner
spring.datasource.password=npg_zWY8gwf0KkBy

#Log out sql queries
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.orm.jdbc.bind=TRACE