<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>About &mdash; Yordle Wiki</title>
  <link rel="stylesheet" href="/style.css" />
</head>
<body>

<nav>
  <span class="site-title">YORDLE WIKI</span>
  <a href="/characters/">Home</a>
  <a href="/characters/about">About</a>
  <a href="/characters/add">Add a Character</a>
</nav>

<div class="page-wrapper">
  <h1 style="font-size:24px; margin-bottom:6px;">About This Site</h1>
  <p class="page-subtitle">CSC340 Assignment 4</p>

  <img
    class="about-img"
    src="https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Veigar_3.jpg"
    alt="Veigar splash art"
  />

  <div class="section">
    <p>
      This site showcases the Yordle champions from the game League of Legends. Yordles are a magical species of small, bipedal (mostly) humanoid creatures originating from the Bandle Realm, a mystical dimention that is almost unreachable by anyone other than a Yordle.
      Despite their size, they tend to punch above their weight class because of their inate magical power, but act as the comic relief since they aren't fully in control of their magic.
    </p>
    <p>
      The five characters featured (Poppy, Veigar, Tristana, Teemo, and Vex) are some of my favorites, and show some of the fun characters of the yorldes.
    </p>
  </div>
 
<footer>
  Yordles Gallery -------------------------------------------------------------------------- Thomas Lambert, CSC 340.
</footer>
 
</body>
</html>